### ISSUE TITLE
Add `Expr.log` and `Expr.exp`

### ISSUE THREAD

**Issue by mt-caret** [mt-caret/polars-ocaml#102]
Should be pretty straightforward:

- https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.log.html
- https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.exp.html

**Comment by ndcroos** [comment]
Hi,

I am interested in this issue. Could you give some more explanation?
It should be added here?
https://github.com/mt-caret/polars-ocaml/blob/main/lib/expr.ml

**Comment by mt-caret** [comment]
Hello! Yup, that's where it should be added; I think you can mimic how some of the other operators are defined (e.g. `Expr.add`/`rust_expr_add`). See the HACKING.md for instructions on building (I think if you just install the OCaml stuff, the Rust compiler should also be installed for you), and feel free to let me know if you run into issues!

**Comment by mt-caret** [comment]
Implemented by https://github.com/mt-caret/polars-ocaml/pull/104.
